# Generated by Django 4.1.5 on 2023-02-06 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='url',
            field=models.CharField(default='https://beyoncecollector-0217.s3.us-east-2.amazonaws.com/IMG_8396.jpg', max_length=200),
            preserve_default=False,
        ),
    ]
