# Generated by Django 4.1.6 on 2023-02-09 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_tour_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beyonce',
            name='tour',
        ),
        migrations.AddField(
            model_name='beyonce',
            name='tour',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main_app.tour'),
            preserve_default=False,
        ),
    ]
